<?php

namespace Drupal\dphi_components\Updates;

class AcquiaSearchFilterFieldsets {

  public static function update10203() {
    $config_factory = \Drupal::configFactory();
    $config = $config_factory->getEditable('views.view.acquia_search');

    $modules = $config->get('dependencies.module');
    if (!in_array('better_exposed_filters', $modules)) {
      $modules[] = 'better_exposed_filters';
      $config->set('dependencies.module', $modules);
    }

    // Update exposed form type and settings
    $config->set('display.default.display_options.exposed_form.type', 'bef');
    $config->set('display.default.display_options.exposed_form.options.text_input_required', 'Select any filter and click on Apply to see results');
    $config->set('display.default.display_options.exposed_form.options.text_input_required_format', 'basic_html');

    // Set up BEF configuration
    $bef_config = [
      'general' => [
        'autosubmit' => FALSE,
        'autosubmit_exclude_textfield' => FALSE,
        'autosubmit_textfield_delay' => 500,
        'autosubmit_textfield_minimum_length' => 3,
        'autosubmit_hide' => FALSE,
        'input_required' => FALSE,
        'allow_secondary' => FALSE,
        'secondary_label' => 'Advanced options',
        'secondary_open' => FALSE,
        'reset_button_always_show' => FALSE,
      ],
      'sort' => [
        'plugin_id' => 'default',
        'advanced' => [
          'combine' => FALSE,
          'combine_rewrite' => '',
          'reset' => FALSE,
          'reset_label' => '',
          'collapsible' => FALSE,
          'collapsible_label' => 'Sort options',
          'is_secondary' => FALSE,
        ],
      ],
      'filter' => [
        'search_api_fulltext' => [
          'plugin_id' => 'default',
          'advanced' => [
            'placeholder_text' => '',
            'rewrite' => [
              'filter_rewrite_values' => '',
              'filter_rewrite_values_key' => FALSE,
            ],
            'collapsible' => FALSE,
            'collapsible_disable_automatic_open' => FALSE,
            'is_secondary' => FALSE,
            'hide_label' => FALSE,
          ],
          'options_show_only_used' => FALSE,
          'options_show_only_used_filtered' => FALSE,
          'options_hide_when_empty' => FALSE,
          'options_show_items_count' => FALSE,
        ],
      ],
    ];

    // Configure taxonomy filters
    $taxonomy_filters = ['field_category', 'field_location', 'field_topics'];
    foreach ($taxonomy_filters as $filter) {
      $bef_config['filter'][$filter] = [
        'plugin_id' => 'bef',
        'advanced' => [
          'sort_options' => FALSE,
          'rewrite' => [
            'filter_rewrite_values' => '',
            'filter_rewrite_values_key' => FALSE,
          ],
          'collapsible' => FALSE,
          'collapsible_disable_automatic_open' => FALSE,
          'is_secondary' => FALSE,
          'hide_label' => FALSE,
        ],
        'select_all_none' => FALSE,
        'select_all_none_nested' => FALSE,
        'display_inline' => FALSE,
        'options_show_only_used' => TRUE,
        'options_show_only_used_filtered' => FALSE,
        'options_hide_when_empty' => TRUE,
        'options_show_items_count' => 0,
      ];
    }

    // Set BEF configuration
    $config->set('display.default.display_options.exposed_form.options.bef', $bef_config);

    // Update banner display type to 'embed'
    $config->set('display.banner.display_plugin', 'embed');
    $config->set('display.banner.display_title', 'Banner');
    $config->set('display.banner.display_options', [
      'fields' => [
        'title' => [
          'id' => 'title',
          'table' => 'search_api_index_acquia_search_index',
          'field' => 'title',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'plugin_id' => 'search_api_field',
          'label' => '',
          'exclude' => FALSE,
          'alter' => [
            'alter_text' => FALSE,
            'text' => '',
            'make_link' => FALSE,
            'path' => '',
            'absolute' => FALSE,
            'external' => FALSE,
            'replace_spaces' => FALSE,
            'path_case' => 'none',
            'trim_whitespace' => FALSE,
            'alt' => '',
            'rel' => '',
            'link_class' => '',
            'prefix' => '',
            'suffix' => '',
            'target' => '',
            'nl2br' => FALSE,
            'max_length' => 0,
            'word_boundary' => TRUE,
            'ellipsis' => TRUE,
            'more_link' => FALSE,
            'more_link_text' => '',
            'more_link_path' => '',
            'strip_tags' => FALSE,
            'trim' => FALSE,
            'preserve_tags' => '',
            'html' => FALSE,
          ],
          'element_type' => '',
          'element_class' => '',
          'element_label_type' => '',
          'element_label_class' => '',
          'element_label_colon' => FALSE,
          'element_wrapper_type' => '',
          'element_wrapper_class' => '',
          'element_default_classes' => TRUE,
          'empty' => '',
          'hide_empty' => FALSE,
          'empty_zero' => FALSE,
          'hide_alter_empty' => TRUE,
          'click_sort_column' => 'value',
          'type' => 'string',
          'settings' => [
            'link_to_entity' => TRUE,
          ],
          'group_column' => 'value',
          'group_columns' => [
          ],
          'group_rows' => TRUE,
          'delta_limit' => 0,
          'delta_offset' => 0,
          'delta_reversed' => FALSE,
          'delta_first_last' => FALSE,
          'multi_type' => 'separator',
          'separator' => ', ',
          'field_api_classes' => FALSE,
          'field_rendering' => TRUE,
          'fallback_handler' => 'search_api',
          'fallback_options' => [
            'link_to_item' => TRUE,
            'use_highlighting' => TRUE,
            'multi_type' => 'separator',
            'multi_separator' => ', ',
          ],
        ],
        'field_short_description' => [
          'id' => 'field_short_description',
          'table' => 'search_api_index_acquia_search_index',
          'field' => 'field_short_description',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'plugin_id' => 'search_api_field',
          'label' => '',
          'exclude' => FALSE,
          'alter' => [
            'alter_text' => FALSE,
            'text' => '',
            'make_link' => FALSE,
            'path' => '',
            'absolute' => FALSE,
            'external' => FALSE,
            'replace_spaces' => FALSE,
            'path_case' => 'none',
            'trim_whitespace' => FALSE,
            'alt' => '',
            'rel' => '',
            'link_class' => '',
            'prefix' => '',
            'suffix' => '',
            'target' => '',
            'nl2br' => FALSE,
            'max_length' => 0,
            'word_boundary' => TRUE,
            'ellipsis' => TRUE,
            'more_link' => FALSE,
            'more_link_text' => '',
            'more_link_path' => '',
            'strip_tags' => FALSE,
            'trim' => FALSE,
            'preserve_tags' => '',
            'html' => FALSE,
          ],
          'element_type' => '',
          'element_class' => '',
          'element_label_type' => '',
          'element_label_class' => '',
          'element_label_colon' => FALSE,
          'element_wrapper_type' => '',
          'element_wrapper_class' => '',
          'element_default_classes' => TRUE,
          'empty' => '',
          'hide_empty' => FALSE,
          'empty_zero' => FALSE,
          'hide_alter_empty' => TRUE,
          'click_sort_column' => 'value',
          'type' => 'text_trimmed',
          'settings' => [
            'trim_length' => 300,
          ],
          'group_column' => 'value',
          'group_columns' => [
          ],
          'group_rows' => TRUE,
          'delta_limit' => 0,
          'delta_offset' => 0,
          'delta_reversed' => FALSE,
          'delta_first_last' => FALSE,
          'multi_type' => 'separator',
          'separator' => ', ',
          'field_api_classes' => FALSE,
          'field_rendering' => TRUE,
          'fallback_handler' => 'search_api',
          'fallback_options' => [
            'link_to_item' => FALSE,
            'use_highlighting' => TRUE,
            'multi_type' => 'separator',
            'multi_separator' => ', ',
          ],
        ],
        'search_api_excerpt' => [
          'id' => 'search_api_excerpt',
          'table' => 'search_api_index_acquia_search_index',
          'field' => 'search_api_excerpt',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'plugin_id' => 'search_api',
          'label' => '',
          'exclude' => FALSE,
          'alter' => [
            'alter_text' => FALSE,
            'text' => '',
            'make_link' => FALSE,
            'path' => '',
            'absolute' => FALSE,
            'external' => FALSE,
            'replace_spaces' => FALSE,
            'path_case' => 'none',
            'trim_whitespace' => FALSE,
            'alt' => '',
            'rel' => '',
            'link_class' => '',
            'prefix' => '',
            'suffix' => '',
            'target' => '',
            'nl2br' => FALSE,
            'max_length' => 0,
            'word_boundary' => TRUE,
            'ellipsis' => TRUE,
            'more_link' => FALSE,
            'more_link_text' => '',
            'more_link_path' => '',
            'strip_tags' => FALSE,
            'trim' => FALSE,
            'preserve_tags' => '',
            'html' => FALSE,
          ],
          'element_type' => '',
          'element_class' => '',
          'element_label_type' => '',
          'element_label_class' => '',
          'element_label_colon' => FALSE,
          'element_wrapper_type' => '',
          'element_wrapper_class' => '',
          'element_default_classes' => TRUE,
          'empty' => '{{body}}',
          'hide_empty' => FALSE,
          'empty_zero' => FALSE,
          'hide_alter_empty' => TRUE,
          'link_to_item' => FALSE,
          'use_highlighting' => FALSE,
          'multi_type' => 'separator',
          'multi_separator' => ', ',
        ],
        'type' => [
          'id' => 'type',
          'table' => 'search_api_index_acquia_search_index',
          'field' => 'type',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'plugin_id' => 'search_api_field',
          'label' => 'Type',
          'exclude' => FALSE,
          'alter' => [
            'alter_text' => FALSE,
            'text' => '',
            'make_link' => FALSE,
            'path' => '',
            'absolute' => FALSE,
            'external' => FALSE,
            'replace_spaces' => FALSE,
            'path_case' => 'none',
            'trim_whitespace' => FALSE,
            'alt' => '',
            'rel' => '',
            'link_class' => '',
            'prefix' => '',
            'suffix' => '',
            'target' => '',
            'nl2br' => FALSE,
            'max_length' => 0,
            'word_boundary' => TRUE,
            'ellipsis' => TRUE,
            'more_link' => FALSE,
            'more_link_text' => '',
            'more_link_path' => '',
            'strip_tags' => FALSE,
            'trim' => FALSE,
            'preserve_tags' => '',
            'html' => FALSE,
          ],
          'element_type' => 'em',
          'element_class' => '',
          'element_label_type' => '',
          'element_label_class' => '',
          'element_label_colon' => TRUE,
          'element_wrapper_type' => '',
          'element_wrapper_class' => '',
          'element_default_classes' => TRUE,
          'empty' => '',
          'hide_empty' => FALSE,
          'empty_zero' => FALSE,
          'hide_alter_empty' => TRUE,
          'click_sort_column' => 'target_id',
          'type' => 'entity_reference_label',
          'settings' => [
            'link' => TRUE,
          ],
          'group_column' => 'target_id',
          'group_columns' => [
          ],
          'group_rows' => TRUE,
          'delta_limit' => 0,
          'delta_offset' => 0,
          'delta_reversed' => FALSE,
          'delta_first_last' => FALSE,
          'multi_type' => 'separator',
          'separator' => ', ',
          'field_api_classes' => FALSE,
          'field_rendering' => FALSE,
          'fallback_handler' => 'search_api_entity',
          'fallback_options' => [
            'link_to_item' => FALSE,
            'use_highlighting' => FALSE,
            'multi_type' => 'separator',
            'multi_separator' => ', ',
            'display_methods' => [
              'node_type' => [
                'display_method' => 'label',
              ],
            ],
          ],
        ],
        'uid' => [
          'id' => 'uid',
          'table' => 'search_api_datasource_acquia_search_index_entity_node',
          'field' => 'uid',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'entity_type' => 'node',
          'plugin_id' => 'search_api_field',
          'label' => '',
          'exclude' => TRUE,
          'alter' => [
            'alter_text' => FALSE,
            'text' => '',
            'make_link' => FALSE,
            'path' => '',
            'absolute' => FALSE,
            'external' => FALSE,
            'replace_spaces' => FALSE,
            'path_case' => 'none',
            'trim_whitespace' => FALSE,
            'alt' => '',
            'rel' => '',
            'link_class' => '',
            'prefix' => '',
            'suffix' => '',
            'target' => '',
            'nl2br' => FALSE,
            'max_length' => 0,
            'word_boundary' => TRUE,
            'ellipsis' => TRUE,
            'more_link' => FALSE,
            'more_link_text' => '',
            'more_link_path' => '',
            'strip_tags' => FALSE,
            'trim' => FALSE,
            'preserve_tags' => '',
            'html' => FALSE,
          ],
          'element_type' => '',
          'element_class' => '',
          'element_label_type' => '',
          'element_label_class' => '',
          'element_label_colon' => FALSE,
          'element_wrapper_type' => '',
          'element_wrapper_class' => '',
          'element_default_classes' => TRUE,
          'empty' => '',
          'hide_empty' => FALSE,
          'empty_zero' => FALSE,
          'hide_alter_empty' => TRUE,
          'click_sort_column' => 'target_id',
          'type' => 'entity_reference_label',
          'settings' => [
            'link' => TRUE,
          ],
          'group_column' => 'target_id',
          'group_columns' => [
          ],
          'group_rows' => TRUE,
          'delta_limit' => 0,
          'delta_offset' => 0,
          'delta_reversed' => FALSE,
          'delta_first_last' => FALSE,
          'multi_type' => 'separator',
          'separator' => ', ',
          'field_api_classes' => FALSE,
          'field_rendering' => TRUE,
          'fallback_handler' => 'search_api_entity',
          'fallback_options' => [
            'link_to_item' => FALSE,
            'use_highlighting' => FALSE,
            'multi_type' => 'separator',
            'multi_separator' => ', ',
            'display_methods' => [
              'user' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
            ],
          ],
        ],
        'created' => [
          'id' => 'created',
          'table' => 'search_api_datasource_acquia_search_index_entity_node',
          'field' => 'created',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'entity_type' => 'node',
          'plugin_id' => 'search_api_field',
          'label' => '',
          'exclude' => TRUE,
          'alter' => [
            'alter_text' => FALSE,
            'text' => '',
            'make_link' => FALSE,
            'path' => '',
            'absolute' => FALSE,
            'external' => FALSE,
            'replace_spaces' => FALSE,
            'path_case' => 'none',
            'trim_whitespace' => FALSE,
            'alt' => '',
            'rel' => '',
            'link_class' => '',
            'prefix' => '',
            'suffix' => '',
            'target' => '',
            'nl2br' => FALSE,
            'max_length' => 0,
            'word_boundary' => TRUE,
            'ellipsis' => TRUE,
            'more_link' => FALSE,
            'more_link_text' => '',
            'more_link_path' => '',
            'strip_tags' => FALSE,
            'trim' => FALSE,
            'preserve_tags' => '',
            'html' => FALSE,
          ],
          'element_type' => '',
          'element_class' => '',
          'element_label_type' => '',
          'element_label_class' => '',
          'element_label_colon' => FALSE,
          'element_wrapper_type' => '',
          'element_wrapper_class' => '',
          'element_default_classes' => TRUE,
          'empty' => '',
          'hide_empty' => FALSE,
          'empty_zero' => FALSE,
          'hide_alter_empty' => TRUE,
          'click_sort_column' => 'value',
          'type' => 'timestamp',
          'settings' => [
            'date_format' => 'medium',
            'custom_date_format' => '',
            'timezone' => '',
            'tooltip' => [
              'date_format' => '',
              'custom_date_format' => '',
            ],
            'time_diff' => [
              'enabled' => FALSE,
              'future_format' => '@interval hence',
              'past_format' => '@interval ago',
              'granularity' => 2,
              'refresh' => 60,
            ],
          ],
          'group_column' => 'value',
          'group_columns' => [
          ],
          'group_rows' => TRUE,
          'delta_limit' => 0,
          'delta_offset' => 0,
          'delta_reversed' => FALSE,
          'delta_first_last' => FALSE,
          'multi_type' => 'separator',
          'separator' => ', ',
          'field_api_classes' => FALSE,
          'field_rendering' => TRUE,
          'fallback_handler' => 'search_api_date',
          'fallback_options' => [
            'date_format' => 'fallback',
            'custom_date_format' => '',
            'timezone' => '',
            'link_to_item' => FALSE,
            'use_highlighting' => FALSE,
            'multi_type' => 'separator',
            'multi_separator' => ', ',
          ],
        ],
        'changed' => [
          'id' => 'changed',
          'table' => 'search_api_datasource_acquia_search_index_entity_node',
          'field' => 'changed',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'entity_type' => 'node',
          'plugin_id' => 'search_api_field',
          'label' => '',
          'exclude' => FALSE,
          'alter' => [
            'alter_text' => FALSE,
            'text' => '',
            'make_link' => FALSE,
            'path' => '',
            'absolute' => FALSE,
            'external' => FALSE,
            'replace_spaces' => FALSE,
            'path_case' => 'none',
            'trim_whitespace' => FALSE,
            'alt' => '',
            'rel' => '',
            'link_class' => '',
            'prefix' => '',
            'suffix' => '',
            'target' => '',
            'nl2br' => FALSE,
            'max_length' => 0,
            'word_boundary' => TRUE,
            'ellipsis' => TRUE,
            'more_link' => FALSE,
            'more_link_text' => '',
            'more_link_path' => '',
            'strip_tags' => FALSE,
            'trim' => FALSE,
            'preserve_tags' => '',
            'html' => FALSE,
          ],
          'element_type' => '',
          'element_class' => '',
          'element_label_type' => '',
          'element_label_class' => '',
          'element_label_colon' => FALSE,
          'element_wrapper_type' => '',
          'element_wrapper_class' => '',
          'element_default_classes' => TRUE,
          'empty' => '',
          'hide_empty' => FALSE,
          'empty_zero' => FALSE,
          'hide_alter_empty' => TRUE,
          'click_sort_column' => 'value',
          'type' => 'timestamp',
          'settings' => [
            'date_format' => 'custom',
            'custom_date_format' => 'd M Y',
            'timezone' => 'Australia/Sydney',
            'tooltip' => [
              'date_format' => '',
              'custom_date_format' => '',
            ],
            'time_diff' => [
              'enabled' => FALSE,
              'future_format' => '@interval hence',
              'past_format' => '@interval ago',
              'granularity' => 2,
              'refresh' => 60,
            ],
          ],
          'group_column' => 'value',
          'group_columns' => [
          ],
          'group_rows' => TRUE,
          'delta_limit' => 0,
          'delta_offset' => 0,
          'delta_reversed' => FALSE,
          'delta_first_last' => FALSE,
          'multi_type' => 'separator',
          'separator' => ', ',
          'field_api_classes' => FALSE,
          'field_rendering' => TRUE,
          'fallback_handler' => 'search_api_date',
          'fallback_options' => [
            'date_format' => 'fallback',
            'custom_date_format' => '',
            'timezone' => '',
            'link_to_item' => FALSE,
            'use_highlighting' => FALSE,
            'multi_type' => 'separator',
            'multi_separator' => ', ',
          ],
        ],
        'field_content_category' => [
          'id' => 'field_content_category',
          'table' => 'search_api_datasource_acquia_search_index_entity_node',
          'field' => 'field_content_category',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'entity_type' => 'node',
          'plugin_id' => 'search_api_field',
          'label' => '',
          'exclude' => FALSE,
          'alter' => [
            'alter_text' => FALSE,
            'text' => '',
            'make_link' => FALSE,
            'path' => '',
            'absolute' => FALSE,
            'external' => FALSE,
            'replace_spaces' => FALSE,
            'path_case' => 'none',
            'trim_whitespace' => FALSE,
            'alt' => '',
            'rel' => '',
            'link_class' => '',
            'prefix' => '',
            'suffix' => '',
            'target' => '',
            'nl2br' => FALSE,
            'max_length' => 0,
            'word_boundary' => TRUE,
            'ellipsis' => TRUE,
            'more_link' => FALSE,
            'more_link_text' => '',
            'more_link_path' => '',
            'strip_tags' => FALSE,
            'trim' => FALSE,
            'preserve_tags' => '',
            'html' => FALSE,
          ],
          'element_type' => '',
          'element_class' => '',
          'element_label_type' => '',
          'element_label_class' => '',
          'element_label_colon' => FALSE,
          'element_wrapper_type' => '',
          'element_wrapper_class' => '',
          'element_default_classes' => TRUE,
          'empty' => 'Content page',
          'hide_empty' => FALSE,
          'empty_zero' => FALSE,
          'hide_alter_empty' => TRUE,
          'click_sort_column' => 'value',
          'type' => 'list_default',
          'settings' => [
          ],
          'group_column' => 'value',
          'group_columns' => [
          ],
          'group_rows' => TRUE,
          'delta_limit' => 0,
          'delta_offset' => 0,
          'delta_reversed' => FALSE,
          'delta_first_last' => FALSE,
          'multi_type' => 'separator',
          'separator' => ', ',
          'field_api_classes' => FALSE,
          'field_rendering' => TRUE,
          'fallback_handler' => 'search_api_numeric',
          'fallback_options' => [
            'set_precision' => FALSE,
            'precision' => 0,
            'decimal' => '.',
            'separator' => ',',
            'format_plural' => FALSE,
            'format_plural_string' => '1@count',
            'prefix' => '',
            'suffix' => '',
            'link_to_item' => FALSE,
            'use_highlighting' => FALSE,
            'multi_type' => 'separator',
            'multi_separator' => ', ',
            'format_plural_values' => [
              0 => '1',
              1 => '@count',
            ],
          ],
        ],
        'field_media_image' => [
          'id' => 'field_media_image',
          'table' => 'search_api_datasource_acquia_search_index_entity_node',
          'field' => 'field_media_image',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'entity_type' => 'node',
          'plugin_id' => 'search_api_field',
          'label' => '',
          'exclude' => FALSE,
          'alter' => [
            'alter_text' => FALSE,
            'text' => '',
            'make_link' => FALSE,
            'path' => '',
            'absolute' => FALSE,
            'external' => FALSE,
            'replace_spaces' => FALSE,
            'path_case' => 'none',
            'trim_whitespace' => FALSE,
            'alt' => '',
            'rel' => '',
            'link_class' => '',
            'prefix' => '',
            'suffix' => '',
            'target' => '',
            'nl2br' => FALSE,
            'max_length' => 0,
            'word_boundary' => TRUE,
            'ellipsis' => TRUE,
            'more_link' => FALSE,
            'more_link_text' => '',
            'more_link_path' => '',
            'strip_tags' => FALSE,
            'trim' => FALSE,
            'preserve_tags' => '',
            'html' => FALSE,
          ],
          'element_type' => '',
          'element_class' => '',
          'element_label_type' => '',
          'element_label_class' => '',
          'element_label_colon' => FALSE,
          'element_wrapper_type' => '',
          'element_wrapper_class' => '',
          'element_default_classes' => TRUE,
          'empty' => '',
          'hide_empty' => FALSE,
          'empty_zero' => FALSE,
          'hide_alter_empty' => TRUE,
          'click_sort_column' => 'target_id',
          'type' => 'entity_reference_entity_view',
          'settings' => [
            'view_mode' => 'full',
          ],
          'group_column' => 'target_id',
          'group_columns' => [
          ],
          'group_rows' => TRUE,
          'delta_limit' => 0,
          'delta_offset' => 0,
          'delta_reversed' => FALSE,
          'delta_first_last' => FALSE,
          'multi_type' => 'separator',
          'separator' => ', ',
          'field_api_classes' => FALSE,
          'field_rendering' => TRUE,
          'fallback_handler' => 'search_api_entity',
          'fallback_options' => [
            'link_to_item' => FALSE,
            'use_highlighting' => FALSE,
            'multi_type' => 'separator',
            'multi_separator' => ', ',
            'display_methods' => [
              'audio' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
              'document' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
              'image' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
              'remote_video' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
              'social_media_icons_footer' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
              'video' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
              'zip' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
            ],
          ],
        ],
        'field_tags' => [
          'id' => 'field_tags',
          'table' => 'search_api_datasource_acquia_search_index_entity_node',
          'field' => 'field_tags',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'entity_type' => 'node',
          'plugin_id' => 'search_api_field',
          'label' => '',
          'exclude' => FALSE,
          'alter' => [
            'alter_text' => FALSE,
            'text' => '',
            'make_link' => FALSE,
            'path' => '',
            'absolute' => FALSE,
            'external' => FALSE,
            'replace_spaces' => FALSE,
            'path_case' => 'none',
            'trim_whitespace' => FALSE,
            'alt' => '',
            'rel' => '',
            'link_class' => '',
            'prefix' => '',
            'suffix' => '',
            'target' => '',
            'nl2br' => FALSE,
            'max_length' => 0,
            'word_boundary' => TRUE,
            'ellipsis' => TRUE,
            'more_link' => FALSE,
            'more_link_text' => '',
            'more_link_path' => '',
            'strip_tags' => FALSE,
            'trim' => FALSE,
            'preserve_tags' => '',
            'html' => FALSE,
          ],
          'element_type' => '',
          'element_class' => '',
          'element_label_type' => '',
          'element_label_class' => '',
          'element_label_colon' => FALSE,
          'element_wrapper_type' => '',
          'element_wrapper_class' => '',
          'element_default_classes' => TRUE,
          'empty' => '',
          'hide_empty' => FALSE,
          'empty_zero' => FALSE,
          'hide_alter_empty' => TRUE,
          'click_sort_column' => 'target_id',
          'type' => 'entity_reference_label',
          'settings' => [
            'link' => TRUE,
          ],
          'group_column' => 'target_id',
          'group_columns' => [
          ],
          'group_rows' => TRUE,
          'delta_limit' => 0,
          'delta_offset' => 0,
          'delta_reversed' => FALSE,
          'delta_first_last' => FALSE,
          'multi_type' => 'separator',
          'separator' => ', ',
          'field_api_classes' => FALSE,
          'field_rendering' => TRUE,
          'fallback_handler' => 'search_api_entity',
          'fallback_options' => [
            'link_to_item' => FALSE,
            'use_highlighting' => FALSE,
            'multi_type' => 'separator',
            'multi_separator' => ', ',
            'display_methods' => [
              'attachment_type' => [
                'display_method' => 'label',
              ],
              'footer_social_icons_connect_with' => [
                'display_method' => 'label',
              ],
              'footer_social_icons_social_media' => [
                'display_method' => 'label',
              ],
              'media_directory' => [
                'display_method' => 'label',
              ],
              'region' => [
                'display_method' => 'label',
              ],
              'related_to' => [
                'display_method' => 'label',
              ],
              'tags' => [
                'display_method' => 'label',
              ],
              'theme' => [
                'display_method' => 'label',
              ],
              'topic' => [
                'display_method' => 'label',
              ],
            ],
          ],
        ],
      ],
      'exposed_form' => [
        'type' => 'bef',
        'options' => [
          'submit_button' => 'Apply',
          'reset_button' => FALSE,
          'reset_button_label' => 'Clear all filters',
          'exposed_sorts_label' => 'Sort by',
          'expose_sort_order' => FALSE,
          'sort_asc_label' => 'Asc',
          'sort_desc_label' => 'Desc',
          'text_input_required' => 'Select any filter and click on Apply to see results',
          'text_input_required_format' => 'basic_html',
          'bef' => [
            'general' => [
              'autosubmit' => FALSE,
              'autosubmit_exclude_textfield' => FALSE,
              'autosubmit_textfield_delay' => 500,
              'autosubmit_textfield_minimum_length' => 3,
              'autosubmit_hide' => FALSE,
              'input_required' => FALSE,
              'allow_secondary' => FALSE,
              'secondary_label' => 'Advanced options',
              'secondary_open' => FALSE,
              'reset_button_always_show' => FALSE,
            ],
            'sort' => [
              'plugin_id' => 'default',
              'advanced' => [
                'combine' => FALSE,
                'combine_rewrite' => '',
                'reset' => FALSE,
                'reset_label' => '',
                'collapsible' => FALSE,
                'collapsible_label' => 'Sort options',
                'is_secondary' => FALSE,
              ],
            ],
            'filter' => [
              'search_api_fulltext' => [
                'plugin_id' => 'default',
                'advanced' => [
                  'placeholder_text' => '',
                  'rewrite' => [
                    'filter_rewrite_values' => '',
                    'filter_rewrite_values_key' => FALSE,
                  ],
                  'collapsible' => FALSE,
                  'collapsible_disable_automatic_open' => FALSE,
                  'is_secondary' => FALSE,
                  'hide_label' => FALSE,
                ],
                'options_show_only_used' => FALSE,
                'options_show_only_used_filtered' => FALSE,
                'options_hide_when_empty' => FALSE,
                'options_show_items_count' => FALSE,
              ],
              'field_category' => [
                'plugin_id' => 'bef',
                'advanced' => [
                  'sort_options' => FALSE,
                  'rewrite' => [
                    'filter_rewrite_values' => '',
                    'filter_rewrite_values_key' => FALSE,
                  ],
                  'collapsible' => FALSE,
                  'collapsible_disable_automatic_open' => FALSE,
                  'is_secondary' => FALSE,
                  'hide_label' => FALSE,
                ],
                'select_all_none' => FALSE,
                'select_all_none_nested' => FALSE,
                'display_inline' => FALSE,
                'options_show_only_used' => FALSE,
                'options_show_only_used_filtered' => FALSE,
                'options_hide_when_empty' => FALSE,
                'options_show_items_count' => 0,
              ],
              'field_location' => [
                'plugin_id' => 'bef',
                'advanced' => [
                  'sort_options' => FALSE,
                  'rewrite' => [
                    'filter_rewrite_values' => '',
                    'filter_rewrite_values_key' => FALSE,
                  ],
                  'collapsible' => FALSE,
                  'collapsible_disable_automatic_open' => FALSE,
                  'is_secondary' => FALSE,
                  'hide_label' => FALSE,
                ],
                'select_all_none' => FALSE,
                'select_all_none_nested' => FALSE,
                'display_inline' => FALSE,
                'options_show_only_used' => FALSE,
                'options_show_only_used_filtered' => FALSE,
                'options_hide_when_empty' => FALSE,
                'options_show_items_count' => 0,
              ],
              'field_topics' => [
                'plugin_id' => 'bef',
                'advanced' => [
                  'sort_options' => FALSE,
                  'rewrite' => [
                    'filter_rewrite_values' => '',
                    'filter_rewrite_values_key' => FALSE,
                  ],
                  'collapsible' => FALSE,
                  'collapsible_disable_automatic_open' => FALSE,
                  'is_secondary' => FALSE,
                  'hide_label' => FALSE,
                ],
                'select_all_none' => FALSE,
                'select_all_none_nested' => FALSE,
                'display_inline' => FALSE,
                'options_show_only_used' => FALSE,
                'options_show_only_used_filtered' => FALSE,
                'options_hide_when_empty' => FALSE,
                'options_show_items_count' => 0,
              ],
            ],
          ],
        ],
      ],
      'sorts' => [
        'search_api_relevance' => [
          'id' => 'search_api_relevance',
          'table' => 'search_api_index_acquia_search_index',
          'field' => 'search_api_relevance',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'plugin_id' => 'search_api',
          'order' => 'DESC',
          'expose' => [
            'label' => 'Relevance',
            'field_identifier' => 'search_api_relevance',
          ],
          'exposed' => TRUE,
        ],
      ],
      'defaults' => [
        'exposed_form' => FALSE,
        'fields' => FALSE,
        'sorts' => FALSE,
      ],
      'display_description' => '',
      'exposed_block' => FALSE,
      'display_extenders' => [
      ],
    ]);

    $unwanted_contexts = [
      'user.node_grants:view',
    ];
    $cache_contexts = $config->get('display.default.cache_metadata.contexts');
    if(!is_null($cache_contexts)){
      $cache_contexts = array_values(array_diff($cache_contexts, $unwanted_contexts));
      $config->set('display.default.cache_metadata.contexts', $cache_contexts);
    }

    $cache_contexts = $config->get('display.page.cache_metadata.contexts');
    if(!is_null($cache_contexts)){
      $cache_contexts = array_values(array_diff($cache_contexts, $unwanted_contexts));
      $config->set('display.page.cache_metadata.contexts', $cache_contexts);
    }

    $cache_contexts = $config->get('display.banner.cache_metadata.contexts');
    if(!is_null($cache_contexts)){
      $cache_contexts = array_values(array_diff($cache_contexts, $unwanted_contexts));
      $config->set('display.banner.cache_metadata.contexts', $cache_contexts);
    }

    $unwanted_tags = [
      'config:search_api.index.acquia_search_index',
      'search_api_list:acquia_search_index',
    ];

    $cache_tags = $config->get('display.default.cache_metadata.tags');
    if(!is_null($cache_tags)){
      $cache_tags = array_values(array_diff($cache_tags, $unwanted_tags));
      $config->set('display.default.cache_metadata.tags', $cache_tags);
    }

    $cache_tags = $config->get('display.page.cache_metadata.tags');
    if(!is_null($cache_tags)){
      $cache_tags = array_values(array_diff($cache_tags, $unwanted_tags));
      $config->set('display.page.cache_metadata.tags', $cache_tags);
    }

    $unwanted_tags[] = 'config:field.storage.node.field_publish_event_date';
    $cache_tags = $config->get('display.banner.cache_metadata.tags');
    if(!is_null($cache_tags)){
      $cache_tags = array_values(array_diff($cache_tags, $unwanted_tags));
      $config->set('display.banner.cache_metadata.tags', $cache_tags);
    }
    // Save the configuration
    $config->save(TRUE);
  }

}
