<?php

namespace Drupal\dphi_components\Updates;

class ContentSearchFilterFieldsets {

  public static function update10203() {
    $config_factory = \Drupal::configFactory();
    $config = $config_factory->getEditable('views.view.contentt_search');

    $modules = $config->get('dependencies.module');
    if (!in_array('better_exposed_filters', $modules)) {
      $modules[] = 'better_exposed_filters';
      $config->set('dependencies.module', $modules);
    }

    // Update exposed form type and settings
    $config->set('display.default.display_options.exposed_form.type', 'bef');
    $config->set('display.default.display_options.exposed_form.options.text_input_required', 'Select any filter and click on Apply to see results');
    $config->set('display.default.display_options.exposed_form.options.text_input_required_format', 'basic_html');

    // Set up BEF configuration
    $bef_config = [
      'general' => [
        'autosubmit' => FALSE,
        'autosubmit_exclude_textfield' => FALSE,
        'autosubmit_textfield_delay' => 500,
        'autosubmit_textfield_minimum_length' => 3,
        'autosubmit_hide' => FALSE,
        'input_required' => FALSE,
        'allow_secondary' => FALSE,
        'secondary_label' => 'Advanced options',
        'secondary_open' => FALSE,
        'reset_button_always_show' => FALSE,
      ],
      'sort' => [
        'plugin_id' => 'default',
        'advanced' => [
          'combine' => FALSE,
          'combine_rewrite' => '',
          'reset' => FALSE,
          'reset_label' => '',
          'collapsible' => FALSE,
          'collapsible_label' => 'Sort options',
          'is_secondary' => FALSE,
        ],
      ],
      'filter' => [
        'search_api_fulltext' => [
          'plugin_id' => 'default',
          'advanced' => [
            'placeholder_text' => '',
            'rewrite' => [
              'filter_rewrite_values' => '',
              'filter_rewrite_values_key' => FALSE,
            ],
            'collapsible' => FALSE,
            'collapsible_disable_automatic_open' => FALSE,
            'is_secondary' => FALSE,
            'hide_label' => FALSE,
          ],
          'options_show_only_used' => FALSE,
          'options_show_only_used_filtered' => FALSE,
          'options_hide_when_empty' => FALSE,
          'options_show_items_count' => FALSE,
        ],
      ],
    ];

    // Configure taxonomy filters
    $taxonomy_filters = ['field_category', 'field_location', 'field_topics'];
    foreach ($taxonomy_filters as $filter) {
      $bef_config['filter'][$filter] = [
        'plugin_id' => 'bef',
        'advanced' => [
          'sort_options' => FALSE,
          'rewrite' => [
            'filter_rewrite_values' => '',
            'filter_rewrite_values_key' => FALSE,
          ],
          'collapsible' => FALSE,
          'collapsible_disable_automatic_open' => FALSE,
          'is_secondary' => FALSE,
          'hide_label' => FALSE,
        ],
        'select_all_none' => FALSE,
        'select_all_none_nested' => FALSE,
        'display_inline' => FALSE,
        'options_show_only_used' => FALSE,
        'options_show_only_used_filtered' => FALSE,
        'options_hide_when_empty' => FALSE,
        'options_show_items_count' => 0,
      ];
    }

    // Set BEF configuration
    $config->set('display.default.display_options.exposed_form.options.bef', $bef_config);

    // Update banner display type to 'embed'
    $config->set('display.banner.display_plugin', 'embed');
    $config->set('display.banner.display_options', [
      'fields' => [
        'title' => [
          'id' => 'title',
          'table' => 'search_api_datasource_content_search_entity_node',
          'field' => 'title',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'entity_type' => 'node',
          'plugin_id' => 'search_api_field',
          'label' => '',
          'exclude' => false,
          'alter' => [
            'alter_text' => false,
            'text' => '',
            'make_link' => false,
            'path' => '',
            'absolute' => false,
            'external' => false,
            'replace_spaces' => false,
            'path_case' => 'none',
            'trim_whitespace' => false,
            'alt' => '',
            'rel' => '',
            'link_class' => '',
            'prefix' => '',
            'suffix' => '',
            'target' => '',
            'nl2br' => false,
            'max_length' => 0,
            'word_boundary' => true,
            'ellipsis' => true,
            'more_link' => false,
            'more_link_text' => '',
            'more_link_path' => '',
            'strip_tags' => false,
            'trim' => false,
            'preserve_tags' => '',
            'html' => false,
          ],
          'element_type' => '',
          'element_class' => '',
          'element_label_type' => '',
          'element_label_class' => '',
          'element_label_colon' => false,
          'element_wrapper_type' => '',
          'element_wrapper_class' => '',
          'element_default_classes' => true,
          'empty' => '',
          'hide_empty' => false,
          'empty_zero' => false,
          'hide_alter_empty' => true,
          'click_sort_column' => 'value',
          'type' => 'string',
          'settings' => [
            'link_to_entity' => true,
          ],
          'group_column' => 'value',
          'group_columns' => [
          ],
          'group_rows' => true,
          'delta_limit' => 0,
          'delta_offset' => 0,
          'delta_reversed' => false,
          'delta_first_last' => false,
          'multi_type' => 'separator',
          'separator' => ', ',
          'field_api_classes' => false,
          'field_rendering' => false,
          'fallback_handler' => 'search_api',
          'fallback_options' => [
            'link_to_item' => true,
            'use_highlighting' => true,
            'multi_type' => 'separator',
            'multi_separator' => ', ',
          ],
        ],
        'field_media_image' => [
          'id' => 'field_media_image',
          'table' => 'search_api_datasource_content_search_entity_node',
          'field' => 'field_media_image',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'entity_type' => 'node',
          'plugin_id' => 'search_api_field',
          'label' => '',
          'exclude' => false,
          'alter' => [
            'alter_text' => false,
            'text' => '',
            'make_link' => false,
            'path' => '',
            'absolute' => false,
            'external' => false,
            'replace_spaces' => false,
            'path_case' => 'none',
            'trim_whitespace' => false,
            'alt' => '',
            'rel' => '',
            'link_class' => '',
            'prefix' => '',
            'suffix' => '',
            'target' => '',
            'nl2br' => false,
            'max_length' => 0,
            'word_boundary' => true,
            'ellipsis' => true,
            'more_link' => false,
            'more_link_text' => '',
            'more_link_path' => '',
            'strip_tags' => false,
            'trim' => false,
            'preserve_tags' => '',
            'html' => false,
          ],
          'element_type' => '',
          'element_class' => '',
          'element_label_type' => '',
          'element_label_class' => '',
          'element_label_colon' => false,
          'element_wrapper_type' => '',
          'element_wrapper_class' => '',
          'element_default_classes' => true,
          'empty' => '',
          'hide_empty' => false,
          'empty_zero' => false,
          'hide_alter_empty' => true,
          'click_sort_column' => 'target_id',
          'type' => 'entity_reference_entity_view',
          'settings' => [
            'view_mode' => 'full',
          ],
          'group_column' => 'target_id',
          'group_columns' => [
          ],
          'group_rows' => true,
          'delta_limit' => 0,
          'delta_offset' => 0,
          'delta_reversed' => false,
          'delta_first_last' => false,
          'multi_type' => 'separator',
          'separator' => ', ',
          'field_api_classes' => false,
          'field_rendering' => true,
          'fallback_handler' => 'search_api_entity',
          'fallback_options' => [
            'link_to_item' => false,
            'use_highlighting' => false,
            'multi_type' => 'separator',
            'multi_separator' => ', ',
            'display_methods' => [
              'audio' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
              'document' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
              'image' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
              'remote_video' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
              'social_media_icons_footer' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
              'video' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
              'zip' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
            ],
          ],
        ],
        'field_short_description' => [
          'id' => 'field_short_description',
          'table' => 'search_api_datasource_content_search_entity_node',
          'field' => 'field_short_description',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'entity_type' => 'node',
          'plugin_id' => 'search_api_field',
          'label' => '',
          'exclude' => false,
          'alter' => [
            'alter_text' => false,
            'text' => '',
            'make_link' => false,
            'path' => '',
            'absolute' => false,
            'external' => false,
            'replace_spaces' => false,
            'path_case' => 'none',
            'trim_whitespace' => false,
            'alt' => '',
            'rel' => '',
            'link_class' => '',
            'prefix' => '',
            'suffix' => '',
            'target' => '',
            'nl2br' => false,
            'max_length' => 0,
            'word_boundary' => true,
            'ellipsis' => true,
            'more_link' => false,
            'more_link_text' => '',
            'more_link_path' => '',
            'strip_tags' => false,
            'trim' => false,
            'preserve_tags' => '',
            'html' => false,
          ],
          'element_type' => '',
          'element_class' => '',
          'element_label_type' => '',
          'element_label_class' => '',
          'element_label_colon' => false,
          'element_wrapper_type' => '',
          'element_wrapper_class' => '',
          'element_default_classes' => true,
          'empty' => '',
          'hide_empty' => false,
          'empty_zero' => false,
          'hide_alter_empty' => true,
          'click_sort_column' => 'value',
          'type' => 'text_trimmed',
          'settings' => [
            'trim_length' => 600,
          ],
          'group_column' => 'value',
          'group_columns' => [
          ],
          'group_rows' => true,
          'delta_limit' => 0,
          'delta_offset' => 0,
          'delta_reversed' => false,
          'delta_first_last' => false,
          'multi_type' => 'separator',
          'separator' => ', ',
          'field_api_classes' => false,
          'field_rendering' => true,
          'fallback_handler' => 'search_api',
          'fallback_options' => [
            'link_to_item' => false,
            'use_highlighting' => false,
            'multi_type' => 'separator',
            'multi_separator' => ', ',
          ],
        ],
        'field_tags' => [
          'id' => 'field_tags',
          'table' => 'search_api_datasource_content_search_entity_node',
          'field' => 'field_tags',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'entity_type' => 'node',
          'plugin_id' => 'search_api_field',
          'label' => '',
          'exclude' => false,
          'alter' => [
            'alter_text' => false,
            'text' => '',
            'make_link' => false,
            'path' => '',
            'absolute' => false,
            'external' => false,
            'replace_spaces' => false,
            'path_case' => 'none',
            'trim_whitespace' => false,
            'alt' => '',
            'rel' => '',
            'link_class' => '',
            'prefix' => '',
            'suffix' => '',
            'target' => '',
            'nl2br' => false,
            'max_length' => 0,
            'word_boundary' => true,
            'ellipsis' => true,
            'more_link' => false,
            'more_link_text' => '',
            'more_link_path' => '',
            'strip_tags' => false,
            'trim' => false,
            'preserve_tags' => '',
            'html' => false,
          ],
          'element_type' => '',
          'element_class' => '',
          'element_label_type' => '',
          'element_label_class' => '',
          'element_label_colon' => false,
          'element_wrapper_type' => '',
          'element_wrapper_class' => '',
          'element_default_classes' => true,
          'empty' => '',
          'hide_empty' => false,
          'empty_zero' => false,
          'hide_alter_empty' => true,
          'click_sort_column' => 'target_id',
          'type' => 'entity_reference_label',
          'settings' => [
            'link' => true,
          ],
          'group_column' => 'target_id',
          'group_columns' => [
          ],
          'group_rows' => true,
          'delta_limit' => 0,
          'delta_offset' => 0,
          'delta_reversed' => false,
          'delta_first_last' => false,
          'multi_type' => 'separator',
          'separator' => ', ',
          'field_api_classes' => false,
          'field_rendering' => true,
          'fallback_handler' => 'search_api_entity',
          'fallback_options' => [
            'link_to_item' => false,
            'use_highlighting' => false,
            'multi_type' => 'separator',
            'multi_separator' => ', ',
            'display_methods' => [
              'attachment_type' => [
                'display_method' => 'label',
              ],
              'footer_social_icons_connect_with' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
              'footer_social_icons_social_media' => [
                'display_method' => 'label',
                'view_mode' => 'default',
              ],
              'region' => [
                'display_method' => 'label',
              ],
              'related_to' => [
                'display_method' => 'label',
              ],
              'tags' => [
                'display_method' => 'label',
              ],
              'theme' => [
                'display_method' => 'label',
              ],
              'topic' => [
                'display_method' => 'label',
              ],
            ],
          ],
        ],
        'search_api_excerpt' => [
          'id' => 'search_api_excerpt',
          'table' => 'search_api_index_content_search',
          'field' => 'search_api_excerpt',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'plugin_id' => 'search_api',
          'label' => '',
          'exclude' => false,
          'alter' => [
            'alter_text' => false,
            'text' => '',
            'make_link' => false,
            'path' => '',
            'absolute' => false,
            'external' => false,
            'replace_spaces' => false,
            'path_case' => 'none',
            'trim_whitespace' => false,
            'alt' => '',
            'rel' => '',
            'link_class' => '',
            'prefix' => '',
            'suffix' => '',
            'target' => '',
            'nl2br' => false,
            'max_length' => 0,
            'word_boundary' => true,
            'ellipsis' => true,
            'more_link' => false,
            'more_link_text' => '',
            'more_link_path' => '',
            'strip_tags' => false,
            'trim' => false,
            'preserve_tags' => '',
            'html' => false,
          ],
          'element_type' => '',
          'element_class' => '',
          'element_label_type' => '',
          'element_label_class' => '',
          'element_label_colon' => false,
          'element_wrapper_type' => '',
          'element_wrapper_class' => '',
          'element_default_classes' => true,
          'empty' => '',
          'hide_empty' => false,
          'empty_zero' => false,
          'hide_alter_empty' => true,
          'link_to_item' => false,
          'use_highlighting' => false,
          'multi_type' => 'separator',
          'multi_separator' => ', ',
        ],
        'field_content_category' => [
          'id' => 'field_content_category',
          'table' => 'search_api_index_content_search',
          'field' => 'field_content_category',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'plugin_id' => 'search_api_field',
          'label' => '',
          'exclude' => false,
          'alter' => [
            'alter_text' => false,
            'text' => '',
            'make_link' => false,
            'path' => '',
            'absolute' => false,
            'external' => false,
            'replace_spaces' => false,
            'path_case' => 'none',
            'trim_whitespace' => false,
            'alt' => '',
            'rel' => '',
            'link_class' => '',
            'prefix' => '',
            'suffix' => '',
            'target' => '',
            'nl2br' => false,
            'max_length' => 0,
            'word_boundary' => true,
            'ellipsis' => true,
            'more_link' => false,
            'more_link_text' => '',
            'more_link_path' => '',
            'strip_tags' => false,
            'trim' => false,
            'preserve_tags' => '',
            'html' => false,
          ],
          'element_type' => '',
          'element_class' => '',
          'element_label_type' => '',
          'element_label_class' => '',
          'element_label_colon' => false,
          'element_wrapper_type' => '',
          'element_wrapper_class' => '',
          'element_default_classes' => true,
          'empty' => '',
          'hide_empty' => false,
          'empty_zero' => false,
          'hide_alter_empty' => true,
          'click_sort_column' => 'value',
          'type' => 'list_default',
          'settings' => [
          ],
          'group_column' => 'value',
          'group_columns' => [
          ],
          'group_rows' => true,
          'delta_limit' => 0,
          'delta_offset' => 0,
          'delta_reversed' => false,
          'delta_first_last' => false,
          'multi_type' => 'separator',
          'separator' => ', ',
          'field_api_classes' => false,
          'field_rendering' => true,
          'fallback_handler' => 'search_api_numeric',
          'fallback_options' => [
            'set_precision' => false,
            'precision' => 0,
            'decimal' => '.',
            'separator' => ',',
            'format_plural' => false,
            'format_plural_string' => '1@count',
            'prefix' => '',
            'suffix' => '',
            'link_to_item' => false,
            'use_highlighting' => false,
            'multi_type' => 'separator',
            'multi_separator' => ', ',
            'format_plural_values' => [
              0 => '1',
              1 => '@count',
            ],
          ],
        ],
      ],
      'sorts' => [
        'search_api_relevance' => [
          'id' => 'search_api_relevance',
          'table' => 'search_api_index_content_search',
          'field' => 'search_api_relevance',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'plugin_id' => 'search_api',
          'order' => 'DESC',
          'expose' => [
            'label' => 'Relevance',
            'field_identifier' => 'search_api_relevance',
          ],
          'exposed' => true,
        ],
        'search_api_id' => [
          'id' => 'search_api_id',
          'table' => 'search_api_index_content_search',
          'field' => 'search_api_id',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'plugin_id' => 'search_api',
          'order' => 'ASC',
          'expose' => [
            'label' => '',
            'field_identifier' => '',
          ],
          'exposed' => false,
        ],
      ],
      'filters' => [
        'search_api_fulltext' => [
          'id' => 'search_api_fulltext',
          'table' => 'search_api_index_content_search',
          'field' => 'search_api_fulltext',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'plugin_id' => 'search_api_fulltext',
          'operator' => 'and',
          'value' => '',
          'group' => 1,
          'exposed' => true,
          'expose' => [
            'operator_id' => 'search_api_fulltext_op',
            'label' => '',
            'description' => '',
            'use_operator' => false,
            'operator' => 'search_api_fulltext_op',
            'operator_limit_selection' => false,
            'operator_list' => [
            ],
            'identifier' => 'input-autocomplete',
            'required' => false,
            'remember' => false,
            'multiple' => false,
            'remember_roles' => [
              'authenticated' => 'authenticated',
              'anonymous' => '0',
              'administrator' => '0',
              'editor' => '0',
            ],
            'expose_fields' => false,
            'placeholder' => '',
            'searched_fields_id' => '',
          ],
          'is_grouped' => false,
          'group_info' => [
            'label' => '',
            'description' => '',
            'identifier' => '',
            'optional' => true,
            'widget' => 'select',
            'multiple' => false,
            'remember' => false,
            'default_group' => 'All',
            'default_group_multiple' => [
            ],
            'group_items' => [
            ],
          ],
          'parse_mode' => 'direct',
          'min_length' => NULL,
          'fields' => [
          ],
        ],
        'status' => [
          'id' => 'status',
          'table' => 'search_api_index_content_search',
          'field' => 'status',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'plugin_id' => 'search_api_boolean',
          'operator' => '=',
          'value' => '1',
          'group' => 1,
          'exposed' => false,
          'expose' => [
            'operator_id' => '',
            'label' => '',
            'description' => '',
            'use_operator' => false,
            'operator' => '',
            'operator_limit_selection' => false,
            'operator_list' => [
            ],
            'identifier' => '',
            'required' => false,
            'remember' => false,
            'multiple' => false,
            'remember_roles' => [
              'authenticated' => 'authenticated',
            ],
          ],
          'is_grouped' => false,
          'group_info' => [
            'label' => '',
            'description' => '',
            'identifier' => '',
            'optional' => true,
            'widget' => 'select',
            'multiple' => false,
            'remember' => false,
            'default_group' => 'All',
            'default_group_multiple' => [
            ],
            'group_items' => [
            ],
          ],
        ],
        'field_category' => [
          'id' => 'field_category',
          'table' => 'search_api_index_content_search',
          'field' => 'field_category',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'plugin_id' => 'search_api_term',
          'operator' => 'or',
          'value' => [
          ],
          'group' => 1,
          'exposed' => true,
          'expose' => [
            'operator_id' => 'field_category_op',
            'label' => 'Category',
            'description' => '',
            'use_operator' => false,
            'operator' => 'field_category_op',
            'operator_limit_selection' => false,
            'operator_list' => [
            ],
            'identifier' => 'field_category',
            'required' => false,
            'remember' => false,
            'multiple' => true,
            'remember_roles' => [
              'authenticated' => 'authenticated',
              'anonymous' => '0',
              'administrator' => '0',
              'editor' => '0',
              'site_admin' => '0',
            ],
            'reduce' => false,
          ],
          'is_grouped' => false,
          'group_info' => [
            'label' => '',
            'description' => '',
            'identifier' => '',
            'optional' => true,
            'widget' => 'select',
            'multiple' => false,
            'remember' => false,
            'default_group' => 'All',
            'default_group_multiple' => [
            ],
            'group_items' => [
            ],
          ],
          'reduce_duplicates' => false,
          'vid' => 'category',
          'type' => 'select',
          'hierarchy' => false,
          'limit' => true,
          'error_message' => true,
        ],
        'field_location' => [
          'id' => 'field_location',
          'table' => 'search_api_index_content_search',
          'field' => 'field_location',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'plugin_id' => 'search_api_term',
          'operator' => 'or',
          'value' => [
          ],
          'group' => 1,
          'exposed' => true,
          'expose' => [
            'operator_id' => 'field_location_op',
            'label' => 'Location',
            'description' => '',
            'use_operator' => false,
            'operator' => 'field_location_op',
            'operator_limit_selection' => false,
            'operator_list' => [
            ],
            'identifier' => 'field_location',
            'required' => false,
            'remember' => false,
            'multiple' => true,
            'remember_roles' => [
              'authenticated' => 'authenticated',
              'anonymous' => '0',
              'administrator' => '0',
              'editor' => '0',
              'site_admin' => '0',
            ],
            'reduce' => false,
          ],
          'is_grouped' => false,
          'group_info' => [
            'label' => '',
            'description' => '',
            'identifier' => '',
            'optional' => true,
            'widget' => 'select',
            'multiple' => false,
            'remember' => false,
            'default_group' => 'All',
            'default_group_multiple' => [
            ],
            'group_items' => [
            ],
          ],
          'reduce_duplicates' => false,
          'vid' => 'location',
          'type' => 'select',
          'hierarchy' => false,
          'limit' => true,
          'error_message' => true,
        ],
        'field_topics' => [
          'id' => 'field_topics',
          'table' => 'search_api_index_content_search',
          'field' => 'field_topics',
          'relationship' => 'none',
          'group_type' => 'group',
          'admin_label' => '',
          'plugin_id' => 'search_api_term',
          'operator' => 'or',
          'value' => [
          ],
          'group' => 1,
          'exposed' => true,
          'expose' => [
            'operator_id' => 'field_topics_op',
            'label' => 'Topics',
            'description' => '',
            'use_operator' => false,
            'operator' => 'field_topics_op',
            'operator_limit_selection' => false,
            'operator_list' => [
            ],
            'identifier' => 'field_topics',
            'required' => false,
            'remember' => false,
            'multiple' => true,
            'remember_roles' => [
              'authenticated' => 'authenticated',
              'anonymous' => '0',
              'administrator' => '0',
              'editor' => '0',
              'site_admin' => '0',
            ],
            'reduce' => false,
          ],
          'is_grouped' => false,
          'group_info' => [
            'label' => '',
            'description' => '',
            'identifier' => '',
            'optional' => true,
            'widget' => 'select',
            'multiple' => false,
            'remember' => false,
            'default_group' => 'All',
            'default_group_multiple' => [
            ],
            'group_items' => [
            ],
          ],
          'reduce_duplicates' => false,
          'vid' => 'topics',
          'type' => 'select',
          'hierarchy' => false,
          'limit' => true,
          'error_message' => true,
        ],
      ],
      'filter_groups' => [
        'operator' => 'AND',
        'groups' => [
          1 => 'AND',
        ],
      ],
      'defaults' => [
        'exposed_form' => true,
        'fields' => false,
        'sorts' => false,
        'filters' => false,
        'filter_groups' => false,
      ],
      'display_description' => '',
      'display_extenders' => [
      ],
    ]);

    $config->set('display.page_1.display_options', [
      'exposed_form' => [
        'type' => 'bef',
        'options' => [
          'submit_button' => 'Apply',
          'reset_button' => true,
          'reset_button_label' => 'Clear all filters',
          'exposed_sorts_label' => 'Sort by',
          'expose_sort_order' => false,
          'sort_asc_label' => 'Asc',
          'sort_desc_label' => 'Desc',
          'text_input_required' => 'Select any filter and click on Apply to see results',
          'text_input_required_format' => 'basic_html',
          'bef' => [
            'general' => [
              'autosubmit' => false,
              'autosubmit_exclude_textfield' => false,
              'autosubmit_textfield_delay' => 500,
              'autosubmit_textfield_minimum_length' => 3,
              'autosubmit_hide' => false,
              'input_required' => false,
              'allow_secondary' => false,
              'secondary_label' => 'Advanced options',
              'secondary_open' => false,
              'reset_button_always_show' => false,
            ],
            'sort' => [
              'plugin_id' => 'default',
              'advanced' => [
                'combine' => false,
                'combine_rewrite' => '',
                'reset' => false,
                'reset_label' => '',
                'collapsible' => false,
                'collapsible_label' => 'Sort options',
                'is_secondary' => false,
              ],
            ],
            'filter' => [
              'search_api_fulltext' => [
                'plugin_id' => 'default',
                'advanced' => [
                  'placeholder_text' => '',
                  'rewrite' => [
                    'filter_rewrite_values' => '',
                    'filter_rewrite_values_key' => false,
                  ],
                  'collapsible' => false,
                  'collapsible_disable_automatic_open' => false,
                  'is_secondary' => false,
                  'hide_label' => false,
                ],
                'options_show_only_used' => false,
                'options_show_only_used_filtered' => false,
                'options_hide_when_empty' => false,
                'options_show_items_count' => false,
              ],
              'field_theme' => [
                'plugin_id' => 'bef',
                'advanced' => [
                  'sort_options' => false,
                  'rewrite' => [
                    'filter_rewrite_values' => '',
                    'filter_rewrite_values_key' => false,
                  ],
                  'collapsible' => false,
                  'collapsible_disable_automatic_open' => false,
                  'is_secondary' => false,
                  'hide_label' => false,
                ],
                'select_all_none' => false,
                'select_all_none_nested' => false,
                'display_inline' => false,
                'options_show_only_used' => true,
                'options_show_only_used_filtered' => false,
                'options_hide_when_empty' => true,
                'options_show_items_count' => 0,
              ],
              'field_category' => [
                'plugin_id' => 'bef',
                'advanced' => [
                  'sort_options' => false,
                  'rewrite' => [
                    'filter_rewrite_values' => '',
                    'filter_rewrite_values_key' => false,
                  ],
                  'collapsible' => false,
                  'collapsible_disable_automatic_open' => false,
                  'is_secondary' => false,
                  'hide_label' => false,
                ],
                'select_all_none' => true,
                'select_all_none_nested' => false,
                'display_inline' => false,
                'options_show_only_used' => true,
                'options_show_only_used_filtered' => false,
                'options_hide_when_empty' => true,
                'options_show_items_count' => 0,
              ],
              'field_location' => [
                'plugin_id' => 'bef',
                'advanced' => [
                  'sort_options' => false,
                  'rewrite' => [
                    'filter_rewrite_values' => '',
                    'filter_rewrite_values_key' => false,
                  ],
                  'collapsible' => false,
                  'collapsible_disable_automatic_open' => false,
                  'is_secondary' => false,
                  'hide_label' => false,
                ],
                'select_all_none' => false,
                'select_all_none_nested' => false,
                'display_inline' => false,
                'options_show_only_used' => true,
                'options_show_only_used_filtered' => false,
                'options_hide_when_empty' => true,
                'options_show_items_count' => 0,
              ],
              'field_topics' => [
                'plugin_id' => 'bef',
                'advanced' => [
                  'sort_options' => false,
                  'rewrite' => [
                    'filter_rewrite_values' => '',
                    'filter_rewrite_values_key' => false,
                  ],
                  'collapsible' => false,
                  'collapsible_disable_automatic_open' => false,
                  'is_secondary' => false,
                  'hide_label' => false,
                ],
                'select_all_none' => false,
                'select_all_none_nested' => false,
                'display_inline' => false,
                'options_show_only_used' => true,
                'options_show_only_used_filtered' => false,
                'options_hide_when_empty' => true,
                'options_show_items_count' => 0,
              ],
            ],
          ],
        ],
      ],
      'defaults' => [
        'exposed_form' => false,
      ],
      'display_extenders' => [
      ],
      'path' => 'search',
    ]);

    $tags = ['config:field.storage.node.field_publish_event_date'];
    $cache_tags = $config->get('display.banner.cache_metadata.tags');
    $cache_tags = (!is_null($cache_tags)) ? array_values(array_diff($cache_tags, $tags)) : $tags;
    $config->set('display.banner.cache_metadata.tags', $cache_tags);

    $cache_tags = $config->get('display.page_1.cache_metadata.tags');
    $cache_tags = (!is_null($cache_tags)) ? array_values(array_diff($cache_tags, $tags)) : $tags;
    $config->set('display.page_1.cache_metadata.tags', $cache_tags);

    // Save the configuration
    $config->save(TRUE);
  }

}
