microcontent.type.*:
  type: config_entity
  label: 'Content type'
  mapping:
    name:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    type_class:
      type: text
      label: 'Background class'
    new_revision:
      type: boolean
      label: 'Whether a new revision should be created by default'
