ckeditor.plugin.indentblock:
  type: mapping
  label: 'Indent block'
  mapping:
    enable:
      type: boolean
      label: 'Enable'
ckeditor5.plugin.ckeditor_indentblock_indent:
  type: config_object
  label: 'CKEditor IndentBlock settings'
  mapping:
    enable:
      type: boolean
      label: 'Enable'
