<?php

/**
 * @file
 * Content lock hooks test: Main functions of the module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\content_lock_hooks_test\Hook\Hooks;

/**
 * Implements hook_content_lock_entity_lockable().
 */
#[LegacyHook]
function content_lock_hooks_test_content_lock_entity_lockable(EntityInterface $entity, array $config, ?string $form_op = NULL): bool {
  return (new Hooks())->contentLockEntityLockable($entity, $config, $form_op);
}
