<?php

/**
 * Implements hook_media_bulk_upload_file_ids_alter().
 *
 * @param array $file_ids
 * @param string $media_bulk_config_id
 *
 * @return void
 */
function media_bulk_upload_dropzonejs_media_bulk_upload_file_ids_alter(array &$file_ids, string $media_bulk_config_id) {
  if (!isset($file_ids['uploaded_files'])) {
    return;
  }

  $fileIds = [];
  $fileStorage = \Drupal::entityTypeManager()->getStorage('file');

  foreach ($file_ids['uploaded_files'] as $fileData) {
    if (!is_array($fileData) || !isset($fileData['path'])) {
      continue;
    }

    /** @var \Drupal\file\FileInterface $fileEntity */
    $fileEntity = $fileStorage->create([
      'uri' => $fileData['path'],
      'uid' => \Drupal::currentUser()->id(),
      'filename' => $fileData['filename'],
    ]);
    $fileEntity->setPermanent();
    $fileEntity->save();
    $fileIds[] = $fileEntity->id();
  }

  if (!empty($fileIds)) {
    $file_ids = $fileIds;
  }
}
