<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Form\FormStateInterface;
use Drupal\file\FileInterface;
use Drupal\media_bulk_upload\Entity\MediaBulkConfigInterface;

/**
 * Implements hook_media_bulk_upload_file_ids_alter().
 *
 * @param array $files_data
 *   The uploaded files data.
 * @param \Drupal\media_bulk_upload\Entity\MediaBulkConfigInterface $media_bulk_config
 *   The bulk media upload config ID.
 *
 * @return void
 */
function media_bulk_upload_dropzonejs_media_bulk_upload_files_alter(array &$files_data, MediaBulkConfigInterface $media_bulk_config) {
  if (!isset($files_data['uploaded_files'])) {
    return;
  }

  $files = [];
  $file_storage = \Drupal::entityTypeManager()->getStorage('file');

  foreach ($files_data['uploaded_files'] as $file_data) {
    if (!is_array($file_data) || !isset($file_data['path'])) {
      continue;
    }

    /** @var \Drupal\file\FileInterface $file_entity */
    $file_entity = $file_storage->create([
      'uri' => $file_data['path'],
      'uid' => \Drupal::currentUser()->id(),
      'filename' => $file_data['filename'],
    ]);
    $file_entity->setTemporary();
    $file_entity->save();
    $metadata = [];
    if ($media_bulk_config->get('show_alt')) {
      $metadata['alt'] = $file_data['metadata']['alt'];
    }
    if ($media_bulk_config->get('show_title')) {
      $metadata['title'] = $file_data['metadata']['title'];
    }
    $files[$file_entity->id()] = [
      'file' => $file_entity,
      'metadata' => $metadata,
    ];
  }

  if (!empty($files)) {
    $files_data = $files;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function media_bulk_upload_dropzonejs_form_media_bulk_upload_form_alter(
  &$form,
  FormStateInterface $form_state
) {

  $form['file_upload']['#type'] = 'dropzonejs';
  $form['file_upload']['#disable_form_buttons'] = '.button.form-submit';
  $form['file_upload']['#dropzone_description'] = new TranslatableMarkup('Click or drop your files here');

  if (isset($form['file_upload']['#upload_validators']['FileExtension']['extensions'])) {
    $form['file_upload']['#extensions'] = $form['file_upload']['#upload_validators']['FileExtension']['extensions'];
  }
}
