<?php

/**
 * @file
 * Contains linky.module..
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function linky_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the linky module.
    case 'help.page.linky':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Link management Drupal 8 style') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_menu_local_actions_alter().
 */
function linky_menu_local_actions_alter(&$localActions) {
  // Don't do anything if add action already has a destination.
  if (!isset($localActions['entity.linky.add_form']['options']['query']['destination'])) {
    /** @var \Drupal\Core\Routing\RouteProviderInterface $routeProvider */
    $routeProvider = \Drupal::service('router.route_provider');
    $path = '/admin/content/linky';
    $routes = $routeProvider->getRoutesByPattern($path);
    if ($routes->count() > 0) {
      $localActions['entity.linky.add_form']['options']['query']['destination'] = $path;
    }
  }
}

/**
 * Implements hook_entity_base_field_info_alter().
 *
 * This hook is needed in order to update the linky 'link' field constraint when
 * a change is made to the additional schemes setting for linky.
 */
function linky_entity_base_field_info_alter(array &$fields, EntityTypeInterface $entity_type) {
  /** @var \Drupal\Core\Field\BaseFieldDefinition $link_field */
  if ($entity_type->id() == 'linky' &&
    !empty($link_field = $fields['link'])) {
    $linky_settings = \Drupal::config('linky.settings');
    $link_field->setConstraints(['LinkyLink' => ['settings' => $linky_settings->get('additional_schemes')]]);
  }
}
