preview_link.settings:
  type: config_object
  mapping:
    display_message:
      type: string
      constraints:
        AllowedValues:
          choices:
            - 'always'
            - 'subsequent'
            - 'never'
    enabled_entity_types:
      type: sequence
      sequence:
        type: sequence
        sequence:
          type: string
    multiple_entities:
      label: Whether Preview Links can reference multiple entities.
      type: boolean
    expiry_seconds:
      type: integer
