# Schema for the configuration files of the Linky module.

field.widget.settings.linky:
  type: field.widget.settings.dynamic_entity_reference_default
  label: 'Linky autocomplete widget display format settings'
  mapping:
    allow_duplicate_urls:
      type: boolean
      label: 'Allow duplicate urls'

field.formatter.settings.linky_label:
  type: field.formatter.settings.dynamic_entity_reference_label
  label: 'Linky label formatter settings'
  mapping:
    parent_entity_label_link_text:
      type: boolean
      label: Link to parent entity'

linky.settings:
  type: config_object
  label: 'Linky settings'
  mapping:
    additional_schemes:
      type: mapping
      label: 'Additional schemes'
      mapping:
        telephone:
          type: boolean
          label: 'Telephone numbers'
        email:
          type: boolean
          label: 'Email addresses'
