<?php

/**
 * @file
 * Main module file for Field States UI.
 */

declare(strict_types = 1);

use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\WidgetInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_third_party_settings_form().
 */
function field_states_ui_field_widget_third_party_settings_form(WidgetInterface $plugin, FieldDefinitionInterface $field_definition, string $form_mode, array $form, FormStateInterface $form_state) {
  return \Drupal::service('plugin.manager.field_states_ui.fieldstate')->settingsForm($plugin, $field_definition, $form_mode, $form, $form_state);
}

/**
 * Implements hook_field_widget_settings_summary_alter().
 */
function field_states_ui_field_widget_settings_summary_alter(array &$summary, array $context): void {
  $field_states = $context['widget']->getThirdPartySettings('field_states_ui');
  if (!empty($field_states['field_states'])) {
    $summary[] = t('Field States applied.');
  }
}

/**
 * Implements hook_field_widget_complete_form_alter().
 */
function field_states_ui_field_widget_complete_form_alter(array &$field_widget_complete_form, FormStateInterface $form_state, array $context): void {
  // Don't show on default value forms.
  if ($context['default']) {
    return;
  }
  \Drupal::service('plugin.manager.field_states_ui.fieldstate')->apply($field_widget_complete_form['widget'], $form_state, $context);
}

/**
 * Implements hook_theme().
 */
function field_states_ui_theme(): array {
  return [
    'field_states_ui_summary' => [
      'variables' => ['data' => []],
    ],
  ];
}
