################
# DrupalCI GitLabCI template
#
# Project page:  https://git.drupalcode.org/project/gitlab_templates/
# Documentation: https://project.pages.drupalcode.org/gitlab_templates/
################

include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

# Pipeline configuration variables
variables:
  OPT_IN_TEST_CURRENT: 1
  OPT_IN_TEST_MAX_PHP: 1
  OPT_IN_TEST_PREVIOUS_MAJOR: 1
  _PHPUNIT_CONCURRENT: 1
  _SHOW_ENVIRONMENT_VARIABLES: 1
  _ALL_VALIDATE_ALLOW_FAILURE: 0

.composer-base:
  after_script:
    - vendor/bin/drush status

# Modify the 'current' variant to run Drupal 10 not 11. This has the benefit
# that all validation and linting jobs will be run at Drupal 10.
# Hold the PHP version at 8.3 because 3rd-party modules have deprecations in 8.4
composer:
  variables:
    DRUPAL_CORE: $CORE_PREVIOUS_STABLE
    PHP_VERSION: 8.3

composer (max PHP version):
  variables:
    DRUPAL_CORE: $CORE_PREVIOUS_STABLE
    PHP_VERSION: 8.4
  # Using when: manual needs 'allow failure: true' otherwise the overall pipeline status shows 'blocked'
  rules:
    - !reference [ .opt-in-max-php-rule ]
    - !reference [ .check-max-php-version-rule ]
    - when: manual
      allow_failure: true

# Modify the 'previous major' variant to run Drupal 9.
composer (previous major):
  variables:
    DRUPAL_CORE: ^9.5
    PHP_VERSION: 8.1
    PHP_IMAGE_VARIANT: apache

phpunit:
  before_script:
    # Patch to disable strict config schema validation on older versions of core.
    # See https://www.drupal.org/project/scheduler/issues/3451750
    - pwd
    - |
      vendor/bin/drush status | awk "NR==1{print \$4}" | grep -E '^(8.|9.|10.2)' \
      && echo 'Core version is before 10.3, patching to remove strict config validation' \
      && patch -p1 < tests/3502119-strict-config-schema-false.patch
  variables:
    MINK_DRIVER_ARGS_WEBDRIVER: $MINK_DRIVER_ARGS_WEBDRIVER_LEGACY
