<?php

/**
 * @file
 * Contains tfa_mail_otp.module.
 */

/**
 * Implements hook_mail().
 */
use Drupal\Component\Render\PlainTextOutput;

/**
 * Implements hook_mail().
 */
function tfa_email_otp_mail($key, &$message, $params) {
  $token_service = \Drupal::token();
  $language_manager = \Drupal::languageManager();
  $variables = [
    'user' => $params['account'],
  ];

  $language = $language_manager->getLanguage($params['account']->getPreferredLangcode());
  $original_language = $language_manager->getConfigOverrideLanguage();
  $language_manager->setConfigOverrideLanguage($language);
  $tfa_config = \Drupal::config('tfa.settings');

  $token_options = [
    'langcode' => $message['langcode'],
    'clear' => FALSE,
  ];

  // Allow parameters to take over the message.
  if (!empty($params['message'])) {
    $subject = $params['message']['subject'];
    $body = $params['message']['body'];

    if (!empty($params['message']['from'])) {
      $message['from'] = $params['message']['from'];
    }
  }
  else {
    $mail_setting = $tfa_config->get('validation_plugin_settings.tfa_email_otp.email_setting');
    $subject = $mail_setting['subject'] ?? '[site:name] Authentication code';
    $body = $mail_setting['body'] ?? '[user:display-name],

This code is valid for [length] minutes. Your code is: [code]

This code will expire once you have logged in.';
  }

  $subject = $token_service->replace($subject, $variables, $token_options);
  $message['subject'] = PlainTextOutput::renderFromHtml($subject);
  $message['body'][] = $token_service->replace($body, $variables, $token_options);

  $language_manager->setConfigOverrideLanguage($original_language);
}
